/* Autocompletado local para “Añadir obra”.
 * Catálogo curado de repertorio pianístico canónico; no contiene partituras.
 */
(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.WorkCatalog=api;})(typeof window!=='undefined'?window:globalThis,function(root){
'use strict';
const W=[];
const add=(composer,title,catalog='',key='',duration=0,aliases=[])=>W.push({composer,title,catalog,key,duration:duration||null,aliases:Array.isArray(aliases)?aliases:[]});
const many=(composer,rows)=>rows.forEach(r=>add(composer,...r));

// Bach · WTC, suites, partitas y grandes ciclos.
const bach='Johann Sebastian Bach';
const bachKeys=['C major','C minor','C-sharp major','C-sharp minor','D major','D minor','E-flat major','E-flat minor','E major','E minor','F major','F minor','F-sharp major','F-sharp minor','G major','G minor','A-flat major','G-sharp minor','A major','A minor','B-flat major','B-flat minor','B major','B minor'];
bachKeys.forEach((key,i)=>add(bach,`Well-Tempered Clavier I: Prelude and Fugue No. ${i+1}`,`BWV ${846+i}`,key,0,[`WTC 1 ${i+1}`,`Clave bien temperado 1 ${i+1}`]));
bachKeys.forEach((key,i)=>add(bach,`Well-Tempered Clavier II: Prelude and Fugue No. ${i+1}`,`BWV ${870+i}`,key,0,[`WTC 2 ${i+1}`,`Clave bien temperado 2 ${i+1}`,...(870+i===893?['WTC II B minor','Preludio y fuga si menor libro 2']:[])]));
[['Partita No. 1','BWV 825','B-flat major'],['Partita No. 2','BWV 826','C minor'],['Partita No. 3','BWV 827','A minor'],['Partita No. 4','BWV 828','D major'],['Partita No. 5','BWV 829','G major'],['Partita No. 6','BWV 830','E minor'],['English Suite No. 1','BWV 806','A major'],['English Suite No. 2','BWV 807','A minor'],['English Suite No. 3','BWV 808','G minor'],['English Suite No. 4','BWV 809','F major'],['English Suite No. 5','BWV 810','E minor'],['English Suite No. 6','BWV 811','D minor'],['French Suite No. 1','BWV 812','D minor'],['French Suite No. 2','BWV 813','C minor'],['French Suite No. 3','BWV 814','B minor'],['French Suite No. 4','BWV 815','E-flat major'],['French Suite No. 5','BWV 816','G major'],['French Suite No. 6','BWV 817','E major']].forEach(r=>add(bach,r[0],r[1],r[2]));
add(bach,'Goldberg Variations','BWV 988','G major',45,['Variaciones Goldberg']);add(bach,'Italian Concerto','BWV 971','F major',13,['Concierto italiano']);add(bach,'Chromatic Fantasia and Fugue','BWV 903','D minor',12,['Fantasia cromatica y fuga']);

// Beethoven · las 32 sonatas.
const beethoven='Ludwig van Beethoven';
const beethOps=['Op. 2 No. 1','Op. 2 No. 2','Op. 2 No. 3','Op. 7','Op. 10 No. 1','Op. 10 No. 2','Op. 10 No. 3','Op. 13','Op. 14 No. 1','Op. 14 No. 2','Op. 22','Op. 26','Op. 27 No. 1','Op. 27 No. 2','Op. 28','Op. 31 No. 1','Op. 31 No. 2','Op. 31 No. 3','Op. 49 No. 1','Op. 49 No. 2','Op. 53','Op. 54','Op. 57','Op. 78','Op. 79','Op. 81a','Op. 90','Op. 101','Op. 106','Op. 109','Op. 110','Op. 111'];
const beethKeys=['F minor','A major','C major','E-flat major','C minor','F major','D major','C minor','E major','G major','B-flat major','A-flat major','E-flat major','C-sharp minor','D major','G major','D minor','E-flat major','G minor','G major','C major','F major','F minor','F-sharp major','G major','E-flat major','E minor','A major','B-flat major','E major','A-flat major','C minor'];
const beethNick={8:['Pathétique','Patetica'],14:['Moonlight','Claro de luna'],15:['Pastoral'],17:['Tempest','La tempestad'],21:['Waldstein'],23:['Appassionata'],26:['Les Adieux','Los adioses'],29:['Hammerklavier']};
beethOps.forEach((op,i)=>add(beethoven,`Piano Sonata No. ${i+1}`,op,beethKeys[i],0,[`Beethoven sonata ${i+1}`,...(beethNick[i+1]||[]),...(i===18||i===19?['Sonata Op 49',`Beethoven Op 49 ${i-17}`]:[])]));
add(beethoven,'32 Variations on an Original Theme','WoO 80','C minor',11,['32 variaciones']);

// Mozart.
const mozart='Wolfgang Amadeus Mozart';
const mozSon=[['K. 279','C major'],['K. 280','F major'],['K. 281','B-flat major'],['K. 282','E-flat major'],['K. 283','G major'],['K. 284','D major'],['K. 309','C major'],['K. 310','A minor'],['K. 311','D major'],['K. 330','C major'],['K. 331','A major'],['K. 332','F major'],['K. 333','B-flat major'],['K. 457','C minor'],['K. 533/494','F major'],['K. 545','C major'],['K. 570','B-flat major'],['K. 576','D major']];
mozSon.forEach((r,i)=>add(mozart,`Piano Sonata No. ${i+1}`,r[0],r[1],0,[`Mozart sonata ${i+1}`,r[0].replace('K. ','KV '),...(r[0]==='K. 331'?['Alla turca','Marcha turca']:[]),...(r[0]==='K. 545'?['Sonata facile','Sonata facil']:[])]));
add(mozart,'Fantasia','K. 475','C minor',12,['Fantasía K475']);

// Haydn · selección amplia de sonatas habituales.
const haydn='Joseph Haydn';
[['Hob. XVI:20','C minor'],['Hob. XVI:23','F major'],['Hob. XVI:24','D major'],['Hob. XVI:32','B minor'],['Hob. XVI:33','D major'],['Hob. XVI:34','E minor'],['Hob. XVI:35','C major'],['Hob. XVI:37','D major'],['Hob. XVI:40','G major'],['Hob. XVI:46','A-flat major'],['Hob. XVI:48','C major'],['Hob. XVI:49','E-flat major'],['Hob. XVI:50','C major'],['Hob. XVI:51','D major'],['Hob. XVI:52','E-flat major']].forEach(r=>add(haydn,'Piano Sonata',r[0],r[1],0,[`Haydn ${r[0].replace('Hob. ','')}`]));

// Chopin.
const chopin='Frédéric Chopin';
[['Ballade No. 1','Op. 23','G minor'],['Ballade No. 2','Op. 38','F major'],['Ballade No. 3','Op. 47','A-flat major'],['Ballade No. 4','Op. 52','F minor'],['Scherzo No. 1','Op. 20','B minor'],['Scherzo No. 2','Op. 31','B-flat minor'],['Scherzo No. 3','Op. 39','C-sharp minor'],['Scherzo No. 4','Op. 54','E major'],['Piano Sonata No. 2','Op. 35','B-flat minor'],['Piano Sonata No. 3','Op. 58','B minor'],['Fantaisie','Op. 49','F minor',13],['Barcarolle','Op. 60','F-sharp major',9],['Polonaise-Fantaisie','Op. 61','A-flat major',13],['Polonaise No. 6 “Heroic”','Op. 53','A-flat major',7],['Andante spianato et Grande polonaise brillante','Op. 22','E-flat major',14],['Nocturne','Op. 9 No. 2','E-flat major',5],['Nocturne','Op. 27 No. 2','D-flat major',6],['Nocturne','Op. 48 No. 1','C minor',6]].forEach(r=>add(chopin,r[0],r[1],r[2],r[3]||0));
const op10Keys=['C major','A minor','E major','C-sharp minor','G-flat major','E-flat minor','C major','F major','F minor','A-flat major','E-flat major','C minor'];
const op25Keys=['A-flat major','F minor','F major','A minor','E minor','G-sharp minor','C-sharp minor','D-flat major','G-flat major','B minor','A minor','C minor'];
op10Keys.forEach((k,i)=>add(chopin,`Étude Op. 10 No. ${i+1}`,`Op. 10 No. ${i+1}`,k,0,[`Estudio op 10 ${i+1}`]));op25Keys.forEach((k,i)=>add(chopin,`Étude Op. 25 No. ${i+1}`,`Op. 25 No. ${i+1}`,k,0,[`Estudio op 25 ${i+1}`]));

// Liszt.
const liszt='Franz Liszt';
add(liszt,'Piano Sonata','S.178','B minor',30,['Sonata en si menor']);add(liszt,"Vallée d'Obermann",'S.160/6','E minor',14,['Valle de Obermann','Vallee de Obermann']);add(liszt,'Après une lecture du Dante: Fantasia quasi Sonata','S.161/7','D minor',17,['Dante Sonata','Sonata Dante']);
['Preludio','Molto vivace','Paysage','Mazeppa','Feux follets','Vision','Eroica','Wilde Jagd','Ricordanza','Allegro agitato molto','Harmonies du soir','Chasse-neige'].forEach((t,i)=>add(liszt,`Transcendental Étude No. ${i+1}: ${t}`,'S.139','',0,[`Estudio trascendental ${i+1}`]));
add(liszt,'Liebestraum No. 3','S.541/3','A-flat major',5,['Sueño de amor 3']);add(liszt,'Mephisto Waltz No. 1','S.514','A major',11,['Vals Mefisto 1']);add(liszt,'Funérailles','S.173/7','F minor',11,['Funerailles']);

// Schumann, Brahms, Schubert.
many('Robert Schumann',[["Carnaval","Op. 9","",0,['Carnaval Schumann']],["Fantaisie","Op. 17","C major",0,['Fantasía op 17']],["Symphonic Études","Op. 13","",0,['Estudios sinfónicos']],["Kreisleriana","Op. 16"],["Kinderszenen","Op. 15","",0,['Escenas de niños']],["Arabeske","Op. 18","C major"],["Humoreske","Op. 20","B-flat major"],["Toccata","Op. 7","C major"],["Davidsbündlertänze","Op. 6"],["Piano Sonata No. 1","Op. 11","F-sharp minor"],["Piano Sonata No. 2","Op. 22","G minor"],["Piano Sonata No. 3","Op. 14","F minor"]]);
const brahms='Johannes Brahms';many(brahms,[["Piano Sonata No. 1","Op. 1","C major"],["Piano Sonata No. 2","Op. 2","F-sharp minor"],["Piano Sonata No. 3","Op. 5","F minor"],["Variations and Fugue on a Theme by Handel","Op. 24","B-flat major",27,['Handel Variations','Variaciones Handel']],["Variations on a Theme by Paganini","Op. 35","A minor",25,['Paganini Variations']],["Rhapsody No. 1","Op. 79 No. 1","B minor"],["Rhapsody No. 2","Op. 79 No. 2","G minor"]]);[['Op. 117',3],['Op. 118',6],['Op. 119',4]].forEach(([op,n])=>{for(let i=1;i<=n;i++)add(brahms,`Klavierstück ${op} No. ${i}`,`${op} No. ${i}`);});
const schubert='Franz Schubert';[['D 664','A major'],['D 784','A minor'],['D 840','C major'],['D 845','A minor'],['D 850','D major'],['D 894','G major'],['D 958','C minor'],['D 959','A major'],['D 960','B-flat major']].forEach(r=>add(schubert,'Piano Sonata',r[0],r[1]));add(schubert,'Wanderer Fantasy','D 760','C major',22,['Wanderer-Fantasie','Fantasía Wanderer']);[['D 899','Op. 90'],['D 935','Op. 142']].forEach(([d,op])=>{for(let i=1;i<=4;i++)add(schubert,`Impromptu No. ${i}`,`${d} / ${op} No. ${i}`);});for(let i=1;i<=6;i++)add(schubert,`Moments musicaux No. ${i}`,`D 780 / Op. 94 No. ${i}`);

// Debussy y Ravel.
const debussy='Claude Debussy';const prel1=['Danseuses de Delphes','Voiles','Le vent dans la plaine',"Les sons et les parfums tournent dans l'air du soir","Les collines d'Anacapri",'Des pas sur la neige',"Ce qu'a vu le vent d'ouest",'La fille aux cheveux de lin','La sérénade interrompue','La cathédrale engloutie','La danse de Puck','Minstrels'];const prel2=['Brouillards','Feuilles mortes','La puerta del Vino',"Les fées sont d'exquises danseuses",'Bruyères','General Lavine – eccentric','La terrasse des audiences du clair de lune','Ondine','Hommage à S. Pickwick Esq. P.P.M.P.C.','Canope','Les tierces alternées',"Feux d'artifice"];
prel1.forEach((t,i)=>add(debussy,`Préludes, Book I No. ${i+1}: ${t}`,'L.117'));prel2.forEach((t,i)=>add(debussy,`Préludes, Book II No. ${i+1}: ${t}`,'L.123'));['Pagodes','La soirée dans Grenade','Jardins sous la pluie'].forEach(t=>add(debussy,t,'Estampes, L.100'));add(debussy,'Clair de lune','Suite bergamasque, L.75','',5,['Claro de luna']);add(debussy,"L'isle joyeuse",'L.106','A major',6,['Isle joyeuse']);
const ravel='Maurice Ravel';add(ravel,"Jeux d'eau",'M.30','E major',6,['Juegos de agua']);add(ravel,'Sonatine','M.40','F-sharp minor',12);add(ravel,'Pavane pour une infante défunte','M.19','G major',6,['Pavana para una infanta difunta']);['Noctuelles','Oiseaux tristes',"Une barque sur l'océan",'Alborada del gracioso','La vallée des cloches'].forEach((t,i)=>add(ravel,t,`Miroirs, M.43/${i+1}`));['Ondine','Le Gibet','Scarbo'].forEach((t,i)=>add(ravel,t,`Gaspard de la nuit, M.55/${i+1}`));['Prélude','Fugue','Forlane','Rigaudon','Menuet','Toccata'].forEach((t,i)=>add(ravel,t,`Le Tombeau de Couperin, M.68/${i+1}`));

// Rachmaninoff, Prokofiev y Scriabin.
const rach='Sergei Rachmaninoff';add(rach,'Prelude','Op. 3 No. 2','C-sharp minor',4);for(let i=1;i<=10;i++)add(rach,`Prelude Op. 23 No. ${i}`,`Op. 23 No. ${i}`);for(let i=1;i<=13;i++)add(rach,`Prelude Op. 32 No. ${i}`,`Op. 32 No. ${i}`);for(let i=1;i<=6;i++)add(rach,`Moments musicaux No. ${i}`,`Op. 16 No. ${i}`,'',0,[`Rachmaninov op 16 ${i}`,`Momento musical ${i}`]);add(rach,'Piano Sonata No. 1','Op. 28','D minor');add(rach,'Piano Sonata No. 2','Op. 36','B-flat minor');for(let i=1;i<=8;i++)add(rach,`Étude-tableau Op. 33 No. ${i}`,`Op. 33 No. ${i}`);for(let i=1;i<=9;i++)add(rach,`Étude-tableau Op. 39 No. ${i}`,`Op. 39 No. ${i}`);
const prok='Sergei Prokofiev';[['Op. 1','F minor'],['Op. 14','D minor'],['Op. 28','A minor'],['Op. 29','C minor'],['Op. 38/135','C major'],['Op. 82','A major'],['Op. 83','B-flat major'],['Op. 84','B-flat major'],['Op. 103','C major']].forEach((r,i)=>add(prok,`Piano Sonata No. ${i+1}`,r[0],r[1],0,[`Prokofiev sonata ${i+1}`]));add(prok,'Toccata','Op. 11','D minor',5);add(prok,'Suggestion diabolique','Op. 4 No. 4','C minor',3,['Sugerencia diabólica']);add(prok,'Sarcasms','Op. 17');add(prok,'Visions fugitives','Op. 22');
const scr='Alexander Scriabin';[['Op. 6','F minor'],['Op. 19','G-sharp minor'],['Op. 23','F-sharp minor'],['Op. 30','F-sharp major'],['Op. 53',''],['Op. 62',''],['Op. 64',''],['Op. 66',''],['Op. 68',''],['Op. 70','']].forEach((r,i)=>add(scr,`Piano Sonata No. ${i+1}`,r[0],r[1]));add(scr,'Fantasy','Op. 28','B minor',10,['Fantasía']);add(scr,'Étude','Op. 8 No. 12','D-sharp minor',3);add(scr,'Étude','Op. 42 No. 5','C-sharp minor',3);

// Albéniz, Granados, Scarlatti.
const albeniz='Isaac Albéniz';['Evocación','El Puerto','Fête-dieu à Séville','Rondeña','Almería','Triana','El Albaicín','El Polo','Lavapiés','Málaga','Jerez','Eritaña'].forEach((t,i)=>add(albeniz,t,`Iberia, Book ${Math.floor(i/3)+1} No. ${(i%3)+1}`,'',0,[`Iberia ${i+1}`]));[['Granada','Op. 47 No. 1'],['Cataluña','Op. 47 No. 2'],['Sevilla','Op. 47 No. 3'],['Cádiz','Op. 47 No. 4'],['Asturias','Op. 47 No. 5'],['Aragón','Op. 47 No. 6'],['Castilla','Op. 47 No. 7'],['Cuba','Op. 47 No. 8']].forEach(r=>add(albeniz,r[0],r[1]));add(albeniz,'Córdoba','Op. 232 No. 4','',0,['Cordoba','Cantos de España']);
const granados='Enrique Granados';['Los requiebros','Coloquio en la reja','El fandango de candil','Quejas, o La maja y el ruiseñor','El amor y la muerte','Epílogo: Serenata del espectro'].forEach((t,i)=>add(granados,t,`Goyescas, H.64 No. ${i+1}`, '',0,[`Goyescas ${i+1}`]));['Galante','Oriental','Fandango','Villanesca','Andaluza','Rondalla aragonesa','Valenciana','Sardana','Romántica','Melancólica','Arabesca','Bolero'].forEach((t,i)=>add(granados,t,`Danzas españolas, Op. 37 No. ${i+1}`));
const scarlatti='Domenico Scarlatti';[[27,'B minor'],[87,'B minor'],[96,'D major'],[99,'C minor'],[119,'D major'],[141,'D minor'],[175,'A minor'],[208,'A major'],[213,'D minor'],[239,'F minor'],[253,'E-flat major'],[322,'A major'],[380,'E major'],[430,'D major'],[466,'F minor'],[502,'C major'],[525,'F major'],[533,'A major'],[545,'B-flat major'],[555,'F minor']].forEach(([k,key])=>add(scarlatti,`Keyboard Sonata K. ${k}`,`K. ${k}`,key,0,[`Scarlatti ${k}`,`Sonata K${k}`]));

// Mendelssohn, Tchaikovsky, Ligeti, Bartók, Fauré y Kaprálová.
many('Felix Mendelssohn',[["Rondo capriccioso","Op. 14","E major",7],["Variations sérieuses","Op. 54","D minor",12,['Variaciones serias']],["Fantasia ‘Scottish Sonata’","Op. 28","F-sharp minor",12,['Scottish Sonata']]]);
const tchaik='Pyotr Ilyich Tchaikovsky';['January: At the Fireside','February: Carnival','March: Song of the Lark','April: Snowdrop','May: Starlit Nights','June: Barcarolle','July: Song of the Reaper','August: Harvest','September: The Hunt','October: Autumn Song','November: Troika','December: Christmas'].forEach((t,i)=>add(tchaik,t,`The Seasons, Op. 37a No. ${i+1}`,'',0,[`Las estaciones ${i+1}`]));add(tchaik,'Dumka','Op. 59','C minor',9);add(tchaik,'Grand Sonata','Op. 37','G major',30);
const ligeti='György Ligeti';['Désordre','Cordes à vide','Touches bloquées','Fanfares','Arc-en-ciel','Automne à Varsovie','Galamb borong','Fém','Vertige','Der Zauberlehrling','En suspens','Entrelacs',"L'escalier du diable",'Coloana infinită','White on White','Pour Irina','À bout de souffle','Canon'].forEach((t,i)=>add(ligeti,`Étude No. ${i+1}: ${t}`,`Études, Book ${Math.floor(i/6)+1}`,'',0,[`Ligeti etude ${i+1}`,`Estudio Ligeti ${i+1}`,...(i===6?['Galamb Borong']:[])]));
many('Béla Bartók',[["Piano Sonata","Sz. 80","",14],["Allegro barbaro","Sz. 49","",3],["Out of Doors","Sz. 81","",15,['Al aire libre']],["Romanian Folk Dances","Sz. 56","",6,['Danzas populares rumanas']]]);many('Gabriel Fauré',[["Nocturne No. 1","Op. 33 No. 1","E-flat minor"],["Nocturne No. 2","Op. 33 No. 2","B major"],["Nocturne No. 4","Op. 36","E-flat major"],["Nocturne No. 6","Op. 63","D-flat major"],["Nocturne No. 13","Op. 119","B minor"],["Theme and Variations","Op. 73","C-sharp minor",15,['Tema y variaciones']]]);add('Vítězslava Kaprálová','April Preludes','Op. 13','',12,['Dubnová preludia']);

const composerAliases={
'johann sebastian bach':['bach','js bach'],'ludwig van beethoven':['beethoven'],'wolfgang amadeus mozart':['mozart'],'joseph haydn':['haydn'],'frederic chopin':['chopin'],'franz liszt':['liszt'],'robert schumann':['schumann'],'johannes brahms':['brahms'],'franz schubert':['schubert'],'claude debussy':['debussy'],'maurice ravel':['ravel'],'sergei rachmaninoff':['rachmaninoff','rachmaninov','rajmaninov'],'sergei prokofiev':['prokofiev'],'alexander scriabin':['scriabin','skriabin'],'isaac albeniz':['albeniz'],'enrique granados':['granados'],'domenico scarlatti':['scarlatti'],'felix mendelssohn':['mendelssohn'],'pyotr ilyich tchaikovsky':['tchaikovsky','chaikovsky','tschajkowski','tchaik'],'gyorgy ligeti':['ligeti'],'bela bartok':['bartok'],'gabriel faure':['faure'],'vitezslava kapralova':['kapralova']};
function norm(v){return String(v??'').replace(/œ/gi,'oe').replace(/æ/gi,'ae').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘`´]/g,"'").replace(/\bopus\b/g,'op').replace(/\b(?:numero|number|num|nro|nr|no)\.?\b/g,'no').replace(/n[º°]/g,'no').replace(/\bkv\b/g,'k').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function aliases(e){return composerAliases[norm(e.composer)]||[];}function text(e){return norm([e.title,e.composer,e.catalog,e.key,...e.aliases,...aliases(e)].join(' '));}
function oneEdit(a,b){if(a===b)return true;if(Math.abs(a.length-b.length)>1)return false;let i=0,j=0,d=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++d>1)return false;if(a.length>b.length)i++;else if(b.length>a.length)j++;else{i++;j++;}}return d+(i<a.length||j<b.length?1:0)<=1;}
function score(e,q){q=norm(q);if(!q)return-Infinity;const h=text(e),ht=h.split(' '),qt=q.split(' ');let s=h.includes(q)?100:0;const t=norm(e.title),c=norm(e.composer),al=e.aliases.map(norm),ca=aliases(e).map(norm);if(t.startsWith(q))s+=95;else if(t.includes(q))s+=60;if(c.startsWith(q)||ca.some(a=>a.startsWith(q)))s+=45;if(al.some(a=>a===q))s+=130;for(const token of qt){if(ht.includes(token))s+=14;else if(ht.some(w=>w.startsWith(token)))s+=10;else if(token.length>=5&&ht.some(w=>oneEdit(token,w)))s+=4;else return-Infinity;}const cat=norm(e.catalog);if(cat&&(cat===q||q.includes(cat)))s+=70;return s;}
function searchWorks(works,q,limit=8){if(norm(q).length<2)return[];return works.map((e,i)=>({e,i,s:score(e,q)})).filter(x=>Number.isFinite(x.s)).sort((a,b)=>b.s-a.s||a.i-b.i).slice(0,limit).map(x=>x.e);}
function displayTitle(e){let t=String(e.title||'').trim();if(e.key&&!norm(t).includes(norm(e.key)))t+=' in '+e.key;if(e.catalog&&!norm(t).includes(norm(e.catalog)))t+=', '+e.catalog;return t;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let results=[],selected=-1;
function styles(){if(document.getElementById('workCatalogStyles'))return;const s=document.createElement('style');s.id='workCatalogStyles';s.textContent='.workcat-hint{font-size:9px;color:var(--text3);margin:0 0 7px 2px}.workcat-wrap{position:relative}.workcat-wrap>.modal-input{margin-bottom:0}.workcat-results{display:none;position:absolute;z-index:10120;left:0;right:0;top:calc(100% + 5px);max-height:min(360px,48vh);overflow:auto;padding:5px;background:var(--bg2);border:1px solid var(--border);border-radius:12px;box-shadow:0 18px 45px rgba(0,0,0,.2)}.workcat-results.open{display:block}.workcat-item{display:block;width:100%;text-align:left;border:0;background:transparent;color:var(--text);border-radius:9px;padding:10px 11px;cursor:pointer}.workcat-item:hover,.workcat-item.active{background:color-mix(in srgb,var(--accent) 10%,var(--bg3))}.workcat-title{display:block;font-family:Cormorant Garamond,serif;font-size:17px;font-weight:600;line-height:1.1}.workcat-composer{display:block;margin-top:3px;font-size:10px;color:var(--text2)}.workcat-meta{display:block;margin-top:4px;font-size:8px;color:var(--text3)}.workcat-manual{border-top:1px solid var(--border2);margin-top:3px;padding-top:4px}#modalAddObra .workcat-wrap+#newObraComposer{margin-top:8px}';document.head.appendChild(s);}
function activity(){return document.querySelector('#modalTipoSelector .origen-btn.active')?.dataset.tipo==='actividad';}
function close(){document.getElementById('workcatResults')?.classList.remove('open');selected=-1;}
function choose(i){const e=results[i],name=document.getElementById('newObraName'),comp=document.getElementById('newObraComposer'),dur=document.getElementById('newObraDuracion');if(!e)return;if(name)name.value=displayTitle(e);if(comp)comp.value=e.composer;if(dur&&e.duration&&!dur.value){dur.value=e.duration;dur.dispatchEvent(new Event('input',{bubbles:true}));}name?.dispatchEvent(new Event('change',{bubbles:true}));comp?.dispatchEvent(new Event('change',{bubbles:true}));if(typeof root.updateAddObraPrediccion==='function')root.updateAddObraPrediccion();close();}
function render(q){const p=document.getElementById('workcatResults');if(!p||activity()||String(q).trim().length<2){close();return;}results=searchWorks(W,q,8);selected=-1;p.innerHTML=results.map((e,i)=>`<button type="button" class="workcat-item" data-i="${i}"><span class="workcat-title">${esc(displayTitle(e))}</span><span class="workcat-composer">${esc(e.composer)}</span><span class="workcat-meta">${esc([e.catalog,e.key,e.duration?e.duration+' min aprox.':''].filter(Boolean).join(' · '))}</span></button>`).join('')+`<div class="workcat-manual"><button type="button" class="workcat-item" data-manual="1"><span class="workcat-title">Usar “${esc(String(q).trim())}” tal como lo he escrito</span><span class="workcat-composer">Crear manualmente</span></button></div>`;p.classList.add('open');p.querySelectorAll('[data-i]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>choose(Number(b.dataset.i));});p.querySelector('[data-manual]')?.addEventListener('click',()=>{close();document.getElementById('newObraComposer')?.focus();});}
function init(){const input=document.getElementById('newObraName'),comp=document.getElementById('newObraComposer'),modal=document.getElementById('modalAddObra');if(!input||!comp||!modal||document.getElementById('workcatResults'))return;styles();const hint=document.createElement('div');hint.className='workcat-hint';hint.innerHTML='<strong>Busca una obra</strong> · título, compositor, opus o catálogo';input.before(hint);const wrap=document.createElement('div');wrap.className='workcat-wrap';input.before(wrap);wrap.appendChild(input);const panel=document.createElement('div');panel.id='workcatResults';panel.className='workcat-results';wrap.appendChild(panel);input.placeholder='Beethoven op. 49, Valle de Obermann…';input.autocomplete='off';input.addEventListener('input',()=>render(input.value));input.addEventListener('focus',()=>render(input.value));input.addEventListener('keydown',e=>{const bs=[...panel.querySelectorAll('[data-i]')];if(!panel.classList.contains('open'))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selected=e.key==='ArrowDown'?Math.min(bs.length-1,selected+1):Math.max(0,selected-1);bs.forEach((b,i)=>b.classList.toggle('active',i===selected));bs[selected]?.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&selected>=0){e.preventDefault();choose(selected);}else if(e.key==='Escape')close();});document.addEventListener('mousedown',e=>{if(!wrap.contains(e.target))close();});document.getElementById('modalTipoSelector')?.addEventListener('click',()=>setTimeout(()=>activity()?close():render(input.value),0));new MutationObserver(()=>{const open=modal.classList.contains('open')||modal.style.display==='flex'||modal.style.display==='block';if(open&&!activity()&&!input.value)setTimeout(()=>input.focus(),50);if(!open)close();}).observe(modal,{attributes:true,attributeFilter:['class','style']});}
if(typeof document!=='undefined'){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();}
return{normalizeText:norm,searchWorks,displayTitle,getCatalog:()=>W.slice(),catalogSize:W.length};
});
