// Aggressive research pass — 3 September 2026.
// This file deliberately mixes major cello-only competitions, mixed-instrument opportunities,
// youth/national/institutional competitions, future cycles, dormant series, and lower-confidence
// directory leads. The UI exposes scope + source quality so they are never presented as equivalent.

const upsertCompetition = (c) => {
  const i = competitions.findIndex(x => x.id === c.id);
  if (i >= 0) competitions[i] = { ...competitions[i], ...c };
  else competitions.push(c);
};

const researched = [
  // --- Existing core records: enrich classification / source quality ---
  {id:'vienna26',scope:'mixed',sourceLevel:'official',fitYoungPro:true,tags:['strings','video','Europe']},
  {id:'goritiensis26',scope:'mixed',sourceLevel:'official',fitYoungPro:true,tags:['live','Europe','under-30']},
  {id:'dicc27',scope:'cello',sourceLevel:'official',fitYoungPro:true,tags:['cello-only','major','orchestra','career-support']},
  {id:'fmb27',scope:'institution',sourceLevel:'official',fitYoungPro:'conditional',tags:['Germany','student-only','cello-only']},
  {id:'split27',scope:'cello',sourceLevel:'official',fitYoungPro:true,tags:['cello-only','Europe','concerto']},
  {id:'davidov27',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',tags:['cello-only','Europe','orchestra']},
  {id:'sinfonima27',scope:'institution',sourceLevel:'official',fitYoungPro:'conditional',tags:['instrument-loan','Germany','Switzerland']},
  {id:'geringas27',scope:'cello',sourceLevel:'official',fitYoungPro:true,tags:['cello-only','major','orchestra','Europe']},
  {id:'popper27',scope:'youth',sourceLevel:'official',fitYoungPro:'conditional',tags:['cello-only','Hungary','age-categories']},
  {id:'schoenfeld27',scope:'cello',sourceLevel:'federation',fitYoungPro:true,status:'future',dates:'2027 · exact dates TBA',deadline:'TBA',note:'WFIMC confirms cello, violin and chamber music for the 2027 edition, with the same disciplines also scheduled for 2029 and 2031. The detailed cello page still shows old rules, so do not use its old age/deadline as current.',sources:[['WFIMC 2026 yearbook','https://online.flippingbook.com/view/309220351/119/'],['WFIMC member page','https://www.wfimc.org/member-competition/harbin-schoenfeld-international-string-competition'],['Competition site','https://schoenfeldcompetition.com/cello.php']],tags:['WFIMC','major','China','cello-only']},
  {id:'tchaikovsky27',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',tags:['major','cello-only','Russia']},
  {id:'ard28',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',status:'future',dates:'2028 · exact dates TBA',note:'Confirmed discipline: Violoncello is officially scheduled for the 2028 ARD Competition together with horn, piano and viola. Regulations and application dates are not yet published.',sources:[['Official ARD future disciplines','https://www.ard-musikwettbewerb.de/en/about-the-competition/']],tags:['ARD','major','Munich','cello-only']},
  {id:'enescu28',scope:'cello',sourceLevel:'federation',fitYoungPro:'conditional',status:'future',tags:['WFIMC','major','Bucharest','cello-only']},
  {id:'isangyun28',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',status:'future',tags:['major','Korea','cello-only']},
  {id:'lutoslawski',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',tags:['major','Warsaw','cello-only','cycle-watch']},
  {id:'budapest',scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',tags:['major','Budapest','cello-only','cycle-watch']},
  {id:'cassadoLead',scope:'cello',sourceLevel:'secondary',fitYoungPro:'conditional',tags:['cello-only','cycle-watch','low-confidence']},

  // --- Corrections / records previously embedded in app.js ---
  {id:'pauloLead',name:'International Paulo Cello Competition',year:'Cycle watch',dates:'Last edition: 1–12 Oct 2023 · next call not published',location:'Finland',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'federation',fitYoungPro:'conditional',eligibility:'Next-edition rules TBA. The 2023 edition was open internationally to ages 16–30.',eligClass:'watch',video:'Next edition TBA.',repertoire:'Next edition TBA. Historically a demanding international solo/sonata/concerto programme.',prizes:'Next edition TBA.',jury:'Next edition TBA.',note:'The documented last edition was 2023. Do not treat older online claims of a 2027 edition as confirmed; keep this on the major cycle watchlist until the organiser publishes a current call.',sources:[['2023 international listing','https://gfpa.ngo/event/international-paulo-cello-competition-2023/']],tags:['major','Finland','cello-only','cycle-watch']},
  {id:'janacek28',name:'International Leoš Janáček Competition in Brno · Cello',year:'2028',dates:'2028 · exact dates TBA',location:'Brno, Czech Republic',deadline:'TBA',status:'watch',tier:'professional',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Detailed 2028 cello rules TBA; the competition has a rotating discipline structure.',eligClass:'watch',video:'TBA.',repertoire:'TBA for the next cello cycle.',prizes:'TBA.',jury:'TBA.',note:'Long-range cello cycle watch based on the competition’s rotating disciplines and recent cello history. Wait for the official 2028 call before planning specific repertoire.',sources:[['Official competition','https://hf.jamu.cz/en/projects/international-leos-janacek-competition-in-brno/']],tags:['Brno','cello-only','cycle-watch']},
  {id:'penderecki28',name:'International Krzysztof Penderecki Cello Competition',year:'2028',dates:'Expected 2028 cycle · exact dates TBA',location:'Kraków, Poland',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'2028 rules TBA. The 2023 edition was for cellists aged 16–30.',eligClass:'watch',video:'2028 TBA; 2023 included video preselection.',repertoire:'2028 TBA.',prizes:'2028 TBA.',jury:'2028 TBA.',note:'The organiser explicitly states that the Penderecki cello competition is held every five years; after 2023, 2028 is the expected next cycle. The new rulebook is not yet published.',sources:[['Official 2023 / five-year cycle','https://pendereckicello.amuz.krakow.pl/?lang=en&page_id=113']],tags:['major','Poland','cello-only','five-year-cycle']},
  {id:'mahler27',name:'Gustav Mahler Prize Cello Competition',year:'2027 lead',dates:'2027 · call not yet verified',location:'Online / Czech Republic',deadline:'TBA',status:'unconfirmed',tier:'secondary',major:false,scope:'online',sourceLevel:'secondary',fitYoungPro:'conditional',eligibility:'2027 categories TBA; recent editions included adult as well as youth categories.',eligClass:'watch',video:'Recent editions are video-based; 2027 requirements TBA.',repertoire:'Free-choice style in recent editions; verify new call.',prizes:'TBA.',jury:'TBA.',note:'A recurring online cello competition worth checking, but no 2027 official call was verified during this research pass.',sources:[['Recent organiser site','https://www.mahler.institute/en/cello-2026/']],tags:['online','cello-only','lead']},
  {id:'feuermann',name:'Grand Prix Emanuel Feuermann',year:'Cycle watch',dates:'Last published competition: 2022 · next edition TBA',location:'Berlin, Germany',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next-edition rules TBA.',eligClass:'watch',video:'Next edition TBA. The last published cycle used extensive video preselection.',repertoire:'Next edition TBA.',prizes:'Next edition TBA; the previous edition offered major cash and career-support prizes.',jury:'Next edition TBA.',note:'Prestigious cello-specific Berlin competition; keep on the master radar, but the official site has not yet published a new cycle.',sources:[['Official competition','https://www.gp-emanuelfeuermann.de/en/'],['Last published participation page','https://www.gp-emanuelfeuermann.de/en/participation/']],tags:['major','Berlin','cello-only','cycle-watch']},
  {id:'naumburg',name:'Walter W. Naumburg International Cello Competition',year:'Cycle watch',dates:'Most recent cello edition: 2024 · next cello edition TBA',location:'New York, USA',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next cello edition rules TBA.',eligClass:'watch',video:'TBA.',repertoire:'TBA.',prizes:'TBA.',jury:'TBA.',note:'Major American career competition. The 2026 Naumburg discipline is violin, so there is no current cello application; retain as a future cello-cycle watch.',sources:[['Naumburg Foundation','https://www.naumburg.org/']],tags:['major','USA','cello-only','cycle-watch']},

  // --- Cello-specific competitions missing from the first dossier ---
  {id:'classic-cello',name:'Classic Cello International Competition',year:'Cycle watch',dates:'Last edition: 26 Mar – 6 Apr 2026',location:'London, United Kingdom',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:true,eligibility:'Next-edition rules TBA. The 2026 edition was open to all nationalities and age 40 or younger.',eligClass:'watch',video:'Next edition TBA; 2026 selected 40 competitors through video auditions.',repertoire:'Next edition TBA. The 2026 standalone edition had three demanding live rounds and a Philharmonia Orchestra final.',prizes:'Next edition TBA. 2026 prize fund exceeded €130,000; first prize €50,000.',jury:'Next edition TBA.',note:'A new high-value standalone cello competition. The first standalone edition was in 2026 at the Royal College of Music; no next cycle has been published yet.',sources:[['Official competition','https://classiccello.com/'],['2026 eligibility','https://classiccello.com/about/about-competition.html']],tags:['major','London','cello-only','orchestra']},
  {id:'buchet28',name:'Buchet International Cello Competition',year:'2028 watch',dates:'2026 edition: 26–27 Oct · next biennial festival cycle expected 2028',location:'Belgium',deadline:'TBA',status:'watch',tier:'professional',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:true,eligibility:'Next competition rules TBA; do not reuse the previous age limit without checking.',eligClass:'watch',video:'TBA for the next cycle.',repertoire:'TBA. Recent editions combine video preselection and flexible live recital programming.',prizes:'Next edition TBA; competition laureates also appear at the Brussels Cello Festival.',jury:'Next edition TBA.',note:'Belgium Cello Society describes its Brussels Cello Festival as biennial and runs the Buchet Competition as a flagship project. The 2026 competition selected 16 from more than 100 applicants; watch for the next call.',sources:[['Belgium Cello Society','https://www.brusselscellofestival.com/'],['2026 competition context','https://www.brusselscellofestival.com/2026-announcement']],tags:['Belgium','cello-only','biennial','career']},
  {id:'pierre-fournier',name:'Pierre Fournier Award',year:'Cycle watch',dates:'2026 finals: 15–16 Oct 2026 · applications closed',location:'London, United Kingdom',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next-edition eligibility TBA.',eligClass:'watch',video:'2026 required one link containing live, unedited recordings of five works; next edition TBA.',repertoire:'Next edition TBA. 2026 live rounds drew from a proposed recital programme and concerto.',prizes:'Career package in 2026 included a Wigmore Hall recital, professional film, Champs Hill CD, UK concerto and chamber engagements.',jury:'Next edition TBA.',note:'Excellent career-development prize rather than a conventional cash-only contest. 2026 applications closed on 18 June; no next date published.',sources:[['Official award','https://www.pierrefournieraward.com/'],['2026 audition format','https://www.pierrefournieraward.com/2018-auditions/']],tags:['London','cello-only','Wigmore','career-support']},
  {id:'suggia28',name:'Suggia International Prize',year:'2028 watch',dates:'Last edition: Jun–Jul 2026 · next cycle TBA',location:'Porto, Portugal',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next-edition rules TBA; recent editions target very young professional cellists.',eligClass:'watch',video:'Next edition TBA.',repertoire:'Next edition TBA; recent editions use recital rounds and an orchestral concerto final.',prizes:'Next edition TBA.',jury:'Next edition TBA.',note:'Casa da Música’s prestigious cello prize. The 9th edition concluded in 2026; keep it on the 2028-cycle radar, but wait for a new call before using old age/repertoire rules.',sources:[['Casa da Música 2026 final','https://casadamusica.com/en/news/three-finalists-for-the-final-of-the-9th-suggia-international-prize/']],tags:['Porto','cello-only','orchestra','cycle-watch']},
  {id:'casals28',name:'Pablo Casals International Award for Young Cellists',year:'2028 watch',dates:'Last edition: 2026 · next call TBA',location:'Catalonia, Spain',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next-edition age rules TBA.',eligClass:'watch',video:'Next edition TBA.',repertoire:'Next edition TBA.',prizes:'2026: €18,000 / €12,000 / €6,000 plus concerts and artistic guidance.',jury:'Next edition TBA.',note:'Long-running international young-cellist award with meaningful financial and career support. The 2026 deadline was 7 May; wait for the next official call.',sources:[['Pau Casals Foundation','https://www.paucasals.org/en/pablo-casals-international-award-2026/']],tags:['Spain','cello-only','young-artist','career-support']},
  {id:'ncc-amsterdam28',name:'National Cello Competition · Cello Biennale Amsterdam',year:'2028 watch',dates:'Next biennial cycle expected 2028 · rules TBA',location:'Amsterdam, Netherlands',deadline:'TBA',status:'watch',tier:'professional',major:true,scope:'national',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'National/Netherlands-linked eligibility; exact 2028 rules TBA. The 2026 edition used Dutch nationality and specified Netherlands study/residence/family pathways.',eligClass:'cond',video:'2028 TBA; 2026 used an in-person preliminary round.',repertoire:'2028 TBA.',prizes:'2028 TBA; laureates receive concert opportunities.',jury:'2028 TBA.',note:'Highly relevant national competition inside the Amsterdam Cello Biennale. It is not globally open in the same way as DICC/Geringas, so always check the nationality/study-residence rule.',sources:[['Official 2026 page','https://www.cellobiennale.nl/en/national-cello-competition-2026-qsrt'],['2026 regulations','https://www.cellobiennale.nl/cms_files/File/Regulations%20National%20Cello%20Competition%202026_EN_version%20september%202025.pdf']],tags:['Netherlands','national','cello-only','biennial']},
  {id:'celleast',name:'CellEAST International Competition',year:'Cycle watch',dates:'Last edition: 27–30 May 2026',location:'Bucharest, Romania',deadline:'TBA',status:'watch',tier:'professional',major:false,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Next-edition categories/rules TBA.',eligClass:'watch',video:'TBA.',repertoire:'TBA; the competition also introduced a baroque-cello category in 2026.',prizes:'2026 offered €14,000 total cash plus more than 20 special prizes.',jury:'Next edition TBA.',note:'Romania’s cello-only international competition launched in 2024 and held a second edition in 2026. A future cycle is plausible but not yet officially announced.',sources:[['2026 organiser announcement','https://www.ucimr.ro/celleast-festival-2026-editia-a-v-a/']],tags:['Romania','cello-only','baroque-cello','cycle-watch']},
  {id:'romberg',name:'Romberg Cello Prize',year:'Cycle watch',dates:'Last edition: 20–22 Aug 2026',location:'Münster / Sassenberg, Germany',deadline:'TBA',status:'watch',tier:'professional',major:false,scope:'cello',sourceLevel:'official',fitYoungPro:true,eligibility:'Next-edition rules TBA. 2026 was open to all nationalities, maximum age 35.',eligClass:'watch',video:'2026: unedited YouTube video, free programme, max 20 min. Next edition TBA.',repertoire:'2026 live round: free choice + Bach Suite 3–6 movement; final 30–40 min recital including Bernhard Romberg.',prizes:'2026: €5,000 main prize + two €1,000 encouragement prizes + festival engagement.',jury:'Next edition TBA.',note:'Useful German cello-specific competition with broad age ceiling and relatively flexible repertoire. No next edition has been announced yet.',sources:[['Official 2026 rules','https://romberg-festival.de/romberg-cello-preis-2026/']],tags:['Germany','cello-only','under-35']},
  {id:'jan-vychytil26',name:'Jan Vychytil International Cello Competition',year:'2026',dates:'13–17 Nov 2026',location:'Prague, Czech Republic',deadline:'2026-10-10',status:'open',tier:'youth',major:false,scope:'youth',sourceLevel:'official',fitYoungPro:false,eligibility:'Age/category structure applies; consult the official 2026 category table.',eligClass:'watch',video:'Selected higher categories use a 2026 YouTube video requirement; check category-specific rules.',repertoire:'One round; free repertoire within category time limits; performance from memory compulsory.',prizes:'Category prizes / diplomas; see official rules.',jury:'Published by organiser.',note:'Current, exact, cello-only Prague competition. Primarily a youth/category competition, but it belongs in a complete cello radar.',sources:[['Official 2026 rules','https://www.cellocompetition.com/cellocompetition/page/2']],tags:['Prague','cello-only','youth','open-now']},
  {id:'wilkomirski26',name:'Kazimierz Wiłkomirski International Youth Cello Competition',year:'2026',dates:'2–5 Dec 2026',location:'Poznań, Poland',deadline:'TBA',status:'future',tier:'youth',major:false,scope:'youth',sourceLevel:'official',fitYoungPro:false,eligibility:'Youth age categories; see official 2026 rules.',eligClass:'watch',video:'See category rules.',repertoire:'Two-stage youth cello programme organised by category.',prizes:'Youth competition awards; see official rulebook.',jury:'Official jury appointed by the Centre of Art Education.',note:'18th edition, international and cello-only, held in Poznań in December 2026. Included for completeness even though it targets younger players.',sources:[['Official 2026 rules','https://www.konkurs-wilkomirski.pl/en/competition-rules/']],tags:['Poland','cello-only','youth']},
  {id:'heran27',name:'Heran Cello Competition',year:'2027',dates:'28 Apr – 1 May 2027',location:'Ústí nad Orlicí, Czech Republic',deadline:'TBA',status:'future',tier:'youth',major:false,scope:'youth',sourceLevel:'official',fitYoungPro:false,eligibility:'2027 categories are by birth year: 2017 and younger through the oldest category, 2012–2011.',eligClass:'watch',video:'No preselection video stated on the current programme page.',repertoire:'Published category-specific repertoire; all pieces from memory. Organiser does not provide piano accompaniment.',prizes:'Youth competition awards.',jury:'TBA / organiser publication.',note:'Confirmed 32nd edition. A pure youth cello competition, included so the radar is genuinely comprehensive.',sources:[['Official 2027 announcement','https://www.hvsuo.cz/en/']],tags:['Czech Republic','cello-only','youth']},
  {id:'antonio-janigro',name:'Antonio Janigro International Cello Competition',year:'Cycle watch',dates:'Next call not verified',location:'Croatia',deadline:'TBA',status:'watch',tier:'youth',major:false,scope:'youth',sourceLevel:'secondary',fitYoungPro:'conditional',eligibility:'The competition has historically run youth and older-category formats; current next-edition rules must be checked.',eligClass:'watch',video:'TBA.',repertoire:'TBA.',prizes:'TBA.',jury:'TBA.',note:'Long-established cello competition bearing Janigro’s name. Keep as a cycle lead, but do not rely on historical age/cycle information until a current organiser call appears.',sources:[],tags:['Croatia','cello-only','cycle-watch']},

  // --- Confirmed / serious mixed-instrument competitions that admit cello ---
  {id:'brahms28',name:'International Johannes Brahms Competition · Cello',year:'2028',dates:'25 Sep – 2 Oct 2028',location:'Pörtschach, Austria',deadline:'TBA',status:'future',tier:'professional',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'2028 cello eligibility TBA.',eligClass:'watch',video:'TBA.',repertoire:'TBA for 2028.',prizes:'TBA for 2028.',jury:'TBA.',note:'Officially confirmed future discipline: the 2028 Brahms Competition is Piano and Cello. This is a strong long-range target with exact competition dates already published.',sources:[['Official future competitions','https://www.brahmscompetition.net/en/future-competitions/']],tags:['Austria','confirmed-2028','cello','Brahms']},
  {id:'rosl27',name:'Royal Over-Seas League Annual Music Competition · Strings',year:'2027',dates:'2027 · applications not yet open',location:'London, United Kingdom',deadline:'TBA',status:'future',tier:'major',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:true,eligibility:'Strings section includes cello. ROSL is open to eligible nationalities across the EU/EEA, Switzerland, UK/Commonwealth/former Commonwealth, USA, Japan and South Korea; check 2027 age/category rule when applications open.',eligClass:'watch',video:'Application uses uploaded performance video; 2027 details will appear when the portal opens.',repertoire:'Section-specific free/selected repertoire; 2027 details TBA.',prizes:'Over £75,000 total competition prize money plus mentoring and paid performance opportunities.',jury:'2027 juries TBA.',note:'One of the most useful mixed-instrument career competitions for a young professional cellist. Applications are explicitly not yet open for 2027.',sources:[['Official ROSL competition page','https://rosl.org.uk/art/rosl-annual-music-competition/']],tags:['London','strings','career-support','major']},
  {id:'sphinx27',name:'Sphinx Competition · Strings',year:'2027',dates:'20–23 Jan 2027',location:'Detroit, USA',deadline:'2026-10-20',status:'conditional',tier:'major',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'National string competition serving Black and Latino musicians. Senior division ages 18–30; Junior 17 and under. Check full mission/eligibility requirements before applying.',eligClass:'cond',video:'Online application through Acceptd; see official requirements.',repertoire:'String competition repertoire per official application.',prizes:'Senior: $50,000 / $20,000 / $10,000 + $5,000 Audience Choice; finalists perform with Sphinx Symphony Orchestra. More than $100,000 total prizes.',jury:'2027 jury published by Sphinx, including cello representation.',note:'Major career opportunity but eligibility is mission-specific; therefore marked Conditional rather than generally open.',sources:[['Official 2027 Sphinx Competition','https://www.sphinxmusic.org/sphinx-competition/']],tags:['USA','strings','under-30','mission-specific']},
  {id:'bromsgrove27',name:'Bromsgrove International Musicians’ Competition',year:'2027',dates:'1–5 Jun 2027',location:'Bromsgrove, United Kingdom',deadline:'TBA',status:'future',tier:'professional',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:true,eligibility:'Instrumentalists and pianists of all nationalities, ages 18–25; singers up to 28.',eligClass:'',video:'First stage: two online video recordings. Invited competitors receive free accommodation, meals and practice facilities.',repertoire:'Applicant-selected programme within competition-stage requirements.',prizes:'£4,000 first prize + £1,000 engagement bursary; two finalist prizes £1,500 + £500 bursary each.',jury:'2027 adjudicators published/updated by organiser.',note:'Biennial, genuinely international and particularly practical because on-site accommodation/meals are provided to selected competitors.',sources:[['Official competition','https://bromsgrovecompetition.com/'],['Applicant format','https://bromsgrovecompetition.com/apply.aspx']],tags:['UK','mixed','18-25','video']},
  {id:'shean27',name:'Shean Strings Competition',year:'2027',dates:'17–19 May 2027',location:'Edmonton, Canada',deadline:'TBA',status:'conditional',tier:'professional',major:false,scope:'mixed',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Ages 15–28. Canada residents studying in Canada/abroad, or non-residents who have studied in Canada for at least two academic years.',eligClass:'cond',video:'Six semifinalists are chosen from submitted recordings.',repertoire:'String competition programme; 2027 brochure/rules should be checked.',prizes:'Winner may be invited to perform with Edmonton Symphony Orchestra; current prize schedule via organiser.',jury:'2027 adjudicators TBA/update.',note:'Excellent if the Canada study/residency condition fits; otherwise not eligible.',sources:[['Official competition','https://www.sheancompetition.com/strings/index.html'],['Official eligibility','https://www.sheancompetition.com/about.html']],tags:['Canada','strings','15-28','conditional']},
  {id:'stulberg27',name:'Stulberg International String Competition',year:'2027',dates:'14–16 May 2027',location:'Kalamazoo, Michigan, USA',deadline:'2027-02-01',opens:'2026-10-19',status:'future',tier:'youth',major:true,scope:'youth',sourceLevel:'official',fitYoungPro:false,eligibility:'Violin, viola, cello or double bass; age 19 or under on 1 Jan 2027; current students of the 2027 judges are not eligible.',eligClass:'watch',video:'Application requires an unedited video of one piece with piano or live orchestra accompaniment.',repertoire:'Semifinal: required solo Bach + standard concerto movement(s); final additional concerto movement(s).',prizes:'Major youth string prizes and career exposure; see official 2027 details.',jury:'2027 judges include cellist Anthony Ross.',note:'Top youth string competition. Applications open 19 Oct 2026 and close 1 Feb 2027.',sources:[['Official 2027 details','https://stulberg.org/competition/competition-details/'],['Application guidelines','https://stulberg.org/competition/competition-details/applications-guidelines/']],tags:['USA','strings','youth','under-20']},
  {id:'osm27',name:'OSM Competition · Strings',year:'2027',dates:'2027 · exact dates TBA',location:'Montréal, Canada',deadline:'TBA',status:'future',tier:'major',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:true,eligibility:'2027 strings eligibility TBA on the new call; recent strings rules include violin, viola and cello young-artist categories.',eligClass:'watch',video:'TBA for 2027.',repertoire:'Strings edition includes a J. S. Bach round and orchestral final structure; exact 2027 cello list TBA.',prizes:'Significant cash plus OSM performance/career-development awards; exact 2027 package TBA.',jury:'TBA.',note:'The OSM officially lists 2027 as its Strings edition. A high-priority future mixed competition once the cello rulebook opens.',sources:[['Official OSM upcoming editions','https://www.concoursosm.ca/?lang=en'],['Official prizes framework','https://www.concoursosm.ca/prizes-and-scholarships/?lang=en']],tags:['Canada','strings','major','orchestra']},
  {id:'klein27',name:'Irving M. Klein International String Competition',year:'2027',dates:'Jun 2027 · exact dates TBA',location:'San Francisco, USA',deadline:'2027-01-31',status:'future',tier:'professional',major:true,scope:'mixed',sourceLevel:'secondary',fitYoungPro:'conditional',eligibility:'Historically open internationally to violin, viola, cello and double bass ages 15–23 and not under professional management; verify the 2027 call when it opens.',eligClass:'watch',video:'Around 30 minutes in recent cycles; exact 2027 application TBA.',repertoire:'Recent cycles require solo Bach, concerto and modern/contemporary work; 2027 commissioned cello work is confirmed.',prizes:'Recent first-prize package about $15,000 including cash and paid engagements; verify 2027 final schedule.',jury:'TBA.',note:'The official submission portal explicitly encourages eligible candidates to apply in the 2027 cycle, and a 2027 cello commission is confirmed. Exact 2027 deadline is currently supported by a secondary current listing, so verify when the portal opens.',sources:[['Official submission portal','https://californiamusiccenter.submittable.com/submit'],['2027 competition confirmation','https://arts.ca.gov/grantee/california-music-center-2/']],tags:['USA','strings','15-23','career']},
  {id:'schadt28',name:'National Schadt String Competition · Cello',year:'2028',dates:'3–5 Mar 2028',location:'Allentown, Pennsylvania, USA',deadline:'2027-12-01',opens:'2027-07-01',status:'future',tier:'professional',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'2028 cello eligibility requirements must be checked on the official application page when it opens.',eligClass:'watch',video:'Application format TBA/current page update.',repertoire:'2028 excludes Dvořák, Elgar, Sallinen Op.44, Saint-Saëns No.1 and Strauss Don Quixote from the concerto choice.',prizes:'Top competition prize and performance with Allentown Symphony; full 2028 award details via organiser.',jury:'TBA.',note:'Exact cello edition already confirmed: applications open 1 Jul 2027, close 1 Dec 2027, competition 3–5 Mar 2028.',sources:[['Official Schadt page','https://millersymphonyhall.org/education-engagement/schadt/']],tags:['USA','strings','confirmed-2028','orchestra']},
  {id:'johansen28',name:'Johansen International Competition for Young String Players',year:'2028',dates:'20–23 Mar 2028',location:'Washington, DC, USA',deadline:'Dec 2027',opens:'Mar 2027',status:'future',tier:'youth',major:true,scope:'youth',sourceLevel:'official',fitYoungPro:false,eligibility:'Violin, viola or cello, ages 13–17 during the semifinal/final dates; birth dates 24 Mar 2010–21 Mar 2015. No professional management.',eligClass:'watch',video:'Application includes required videos; preliminary video auditions in Jan 2028.',repertoire:'Bach solo + sonata with piano + concerto/major orchestral work + virtuoso short work + commissioned semifinal work.',prizes:'$67,000 total; per instrument: $10,000 / $7,000 / $5,000 plus special awards.',jury:'TBA.',note:'Confirmed triennial 2028 youth string competition with exact dates and application window.',sources:[['Official 2028 page','https://fmmcfoundation.org/johansen-international-competition/2028-johansen-international-competition/']],tags:['USA','strings','youth','confirmed-2028']},
  {id:'young-texas27',name:'Young Texas Artists Music Competition · Strings',year:'2027',dates:'Mar 2027',location:'Conroe, Texas, USA',deadline:'TBA',status:'conditional',tier:'development',major:false,scope:'national',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Young artist competition with Texas residency/enrolment requirements; strings division includes cello. Verify 2027 rulebook.',eligClass:'cond',video:'Preliminary recording required.',repertoire:'Division-specific programme.',prizes:'Cash/prize and performance opportunities; see 2027 call.',jury:'TBA.',note:'Include only for candidates who satisfy the Texas residence/study condition.',sources:[['Official competition','https://youngtexasartists.org/']],tags:['USA','Texas','strings','conditional']},
  {id:'eckhardt27',name:'Eckhardt-Gramatté National Music Competition · Strings',year:'2027',dates:'30 Apr – 2 May 2027',location:'Brandon, Manitoba, Canada',deadline:'TBA',status:'conditional',tier:'professional',major:false,scope:'national',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Canadian/contemporary-music competition; verify citizenship/residency and age requirements in the 2027 strings call.',eligClass:'cond',video:'Preliminary selection via recording/application.',repertoire:'Strong focus on Canadian and contemporary repertoire.',prizes:'Cash, performances and career opportunities; see 2027 call.',jury:'TBA.',note:'The 50th edition in 2027 is a Strings year. Valuable specialist competition for candidates fitting the Canadian eligibility rules.',sources:[['Official competition','https://e-gre.ca/']],tags:['Canada','strings','contemporary','national']},
  {id:'temsig27',name:'TEMSIG National Young Musicians Competition · Cello',year:'2027',dates:'3–25 Mar 2027',location:'Slovenia',deadline:'2027-01-08',status:'conditional',tier:'development',major:false,scope:'national',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'National/education-linked Slovenian eligibility; cello included. Age limit up to 25 in the published cycle.',eligClass:'cond',video:'See category rules.',repertoire:'National competition category repertoire.',prizes:'National awards.',jury:'TBA.',note:'Current exact 2027 national competition. Relevant only if Slovenian study/citizenship conditions are satisfied.',sources:[['EMCY listing','https://emcy.org/competitions/temsig-slovenian-music-competition-for-youth/']],tags:['Slovenia','national','cello','under-25']},
  {id:'pr-jovens',name:'Prémio Jovens Músicos · Cello',year:'Annual cycle watch',dates:'2027 disciplines TBA',location:'Portugal',deadline:'TBA',status:'watch',tier:'development',major:false,scope:'national',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'Portuguese national/education-linked eligibility; cello appears in rotating annual categories.',eligClass:'cond',video:'TBA.',repertoire:'TBA.',prizes:'National broadcasting/performance prizes.',jury:'TBA.',note:'The 2026 edition included cello; 2027 discipline list is not yet confirmed. Keep on the annual national radar.',sources:[['RTP Antena 2 competition','https://www.rtp.pt/antena2/premio-jovens-musicos/']],tags:['Portugal','national','cycle-watch']},
  {id:'windsor28',name:'Windsor Festival International String Competition',year:'2028 watch',dates:'Next biennial cycle expected 2028',location:'Windsor, United Kingdom',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:true,eligibility:'Next-edition rules TBA. The 2026 edition was for violin, viola, cello and double bass, ages 16–26, all nationalities.',eligClass:'watch',video:'Next edition TBA.',repertoire:'Next edition TBA; recent cycles combine video selection and live rounds.',prizes:'Recent prize package exceeded £40,000 in value, including cash, Royal Philharmonic Orchestra performance, recording and recitals.',jury:'TBA.',note:'Biennial high-value British string competition; 2026 is closed, so keep the expected 2028 cycle on the radar.',sources:[['Official Windsor Festival competition','https://windsorfestival.com/international-string-competition/']],tags:['UK','strings','biennial','career']},
  {id:'heinrich-schiff27',name:'Heinrich Schiff Cello Competition · mdw',year:'2027 lead',dates:'29 Jan 2027 · secondary confirmation',location:'Vienna, Austria',deadline:'TBA',status:'unconfirmed',tier:'institution',major:false,scope:'institution',sourceLevel:'secondary',fitYoungPro:'conditional',eligibility:'Institutional competition for eligible mdw cello students; 2027 official call not yet found.',eligClass:'cond',video:'TBA.',repertoire:'TBA.',prizes:'Institutional prizes/support.',jury:'A juror’s published calendar lists the 2nd mdw Heinrich Schiff Cello Competition on 29 Jan 2027.',note:'Worth tracking for mdw students only. The 2027 date comes from a juror’s professional calendar rather than an updated official mdw competition page, so it is intentionally marked Unconfirmed.',sources:[['Secondary juror calendar','https://celloryo.com/future/']],tags:['Vienna','institution','cello-only','student-only']},

  // --- Dormant / non-actionable but important names so the master radar knows they exist ---
  {id:'anna-kull',name:'Anna Kull International Cello Competition',year:'Dormant',dates:'First edition: Feb 2020',location:'Graz, Austria',deadline:'TBA',status:'dormant',tier:'professional',major:false,scope:'dormant',sourceLevel:'official',fitYoungPro:false,eligibility:'No current edition.',eligClass:'watch',video:'—',repertoire:'—',prizes:'—',jury:'—',note:'KUG explicitly states: “Currently no further edition is planned.” Kept here to prevent wasted searching/planning based on stale old pages.',sources:[['Official KUG competitions page','https://competitions.kug.ac.at/en/competitions']],tags:['dormant','Graz','cello-only']},
  {id:'queen-elisabeth',name:'Queen Elisabeth Competition · Cello',year:'Cycle watch',dates:'Cello 2026 completed · no cello edition announced through 2029',location:'Brussels, Belgium',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'cello',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'No current cello application.',eligClass:'watch',video:'TBA for any future cello return.',repertoire:'TBA.',prizes:'TBA.',jury:'TBA.',note:'One of the world’s top cello competitions, but not currently actionable: the published upcoming disciplines are Voice 2027, Violin 2028 and Piano 2029.',sources:[['Official Queen Elisabeth Competition','https://queenelisabethcompetition.be/']],tags:['major','Belgium','cello-only','cycle-watch']},
  {id:'concours-geneve',name:'Concours de Genève · Cello discipline',year:'Cycle watch',dates:'No current cello edition announced',location:'Geneva, Switzerland',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'mixed',sourceLevel:'federation',fitYoungPro:'conditional',eligibility:'No current cello call.',eligClass:'watch',video:'TBA.',repertoire:'TBA.',prizes:'TBA.',jury:'TBA.',note:'Major WFIMC multidisciplinary competition where cello can return as a rotating discipline. Keep on the cycle radar, but there is no current cello application.',sources:[['WFIMC member directory','https://www.wfimc.org/member-competitions']],tags:['major','Switzerland','rotating-discipline']},
  {id:'markneukirchen',name:'International Instrumental Competition Markneukirchen · Cello cycle',year:'Cycle watch',dates:'2027 disciplines are violin and double bass',location:'Markneukirchen, Germany',deadline:'TBA',status:'watch',tier:'major',major:true,scope:'mixed',sourceLevel:'official',fitYoungPro:'conditional',eligibility:'No cello in the 2027 edition.',eligClass:'watch',video:'—',repertoire:'—',prizes:'—',jury:'—',note:'Important rotating instrumental competition, but 2027 is not cello. Kept so the radar explicitly knows not to treat the 2027 call as relevant.',sources:[['Official competition','https://www.instrumental-competition.de/']],tags:['Germany','rotating-discipline','not-2027']}
];
researched.forEach(upsertCompetition);

// Current public directory sweep. These are deliberately lower confidence than the core list.
// They are useful for discovery and low-friction video opportunities, but the organiser page must be checked before paying any fee.
const directoryLeads = [
  ['london-young26','London Young Musician', '2026','Online, United Kingdom','2026-09-20','2 Sep – 20 Dec 2026'],
  ['svendsen-grieg26','International Svendsen & Grieg Competition 2026','2026','Online, Norway','2026-10-31','20 Aug – 31 Dec 2026'],
  ['saint-saens26','Saint-Saëns International Music Competition','2026','Online, United Kingdom','2026-09-12','15 Aug – 12 Sep 2026'],
  ['vivaldi-online26','Vivaldi International Music Competition 2026','2026','Online, United Kingdom','2026-09-19','15 Aug – 19 Dec 2026'],
  ['string-online-gdansk26','13th String Competition Online','2026','Gdańsk / Online, Poland','2026-09-07','17–22 Sep 2026'],
  ['vineyards26','Music In the Vineyards','2026','Vršac / Oslo / Online','2026-09-30','14–30 Sep 2026'],
  ['loker26','Elizabeth Loker International Concerto Competition','2026–27','Wye Mills, Maryland, USA','2026-12-12','7 Aug 2026 – 14 Mar 2027'],
  ['dvorak-online27','Dvořák Classical Music Competition 2027','2027','Online / Prague, Czech Republic','2027-01-30','Aug 2026 – Jan 2027'],
  ['world-classical26','World Classical Music Awards 2026','2026','Online / London','2026-11-21','19 Jul – 21 Nov 2026'],
  ['max-bruch26','Max Bruch International Music Competition 2026','2026','Online, United Kingdom','2026-11-06','19 Jun – 6 Nov 2026'],
  ['gregynog26','Gregynog Young Musician 2026','2026','Shrewsbury, United Kingdom','2026-10-04','31 Oct 2026'],
  ['concert-star26','Concert Star International Classical Music','2026–27','New York City / Online','TBA','1 Aug 2026 – 25 Jan 2027'],
  ['uk-intl26','UK International Music Competition','2026','London / Online','2026-10-30','6 Jun – 30 Oct 2026'],
  ['world-exceptional26','World Exceptional Musicians Competition 2026','2026','Online / London','2026-10-20','30 May – 20 Oct 2026'],
  ['american-virtuoso26','American Virtuoso International Music Competition','2026–27','Washington, DC / Online','2026-05-31','18 May 2026 – 5 Jun 2027'],
  ['verona26','Premio della Musica di Verona','2026','Verona, Italy','TBA','20 Sep – 6 Dec 2026'],
  ['springs-soloist26','Chamber Orchestra of the Springs Emerging Soloist Competition','2026','Colorado Springs, USA','TBA','21 Apr – 20 Sep 2026'],
  ['padova26','23rd Padova International Music Competition','2026','Padova, Italy','2026-09-10','10 Sep – 10 Dec 2026'],
  ['dresden-auditions26','Soloist Auditions – Concert Season in Germany','2026','Germany / Online','TBA','16 Feb – 30 Nov 2026']
];

directoryLeads.forEach(([id,name,year,location,deadline,dates]) => upsertCompetition({
  id,name,year,dates,location,deadline,
  status: /^2026-0[1-8]/.test(deadline) ? 'closed' : 'open',
  tier:'directory',major:false,scope: location.toLowerCase().includes('online') ? 'online' : 'mixed',sourceLevel:'directory',fitYoungPro:'conditional',
  eligibility:'Directory listing indicates a cello/string/all-instrument category; verify the organiser’s current eligibility, age, nationality and fee rules before applying.',
  eligClass:'watch',video:'Usually video/online or competition-specific; verify organiser page.',repertoire:'Verify the organiser’s rulebook. Do not prepare new repertoire solely from this directory entry.',prizes:'See organiser; directory descriptions may advertise cash, promotion or performance opportunities.',jury:'Verify organiser.',
  note:'Directory lead — included for completeness. Treat as discovery, not as a vetted major competition. Verify organiser identity, rules, fees and prize terms before paying.',
  sources:[['Current Musical Chairs cello directory','https://www.musicalchairs.info/cello/competitions']],tags:['directory-lead','verify-before-paying']
}));

// Ensure duplicate directory-listed core competitions retain their stronger official classification.
['vienna26','goritiensis26','split27'].forEach(id => {
  const c=competitions.find(x=>x.id===id); if(c){c.sourceLevel='official';}
});
