const fmtDate = d => { if(!/^\d{4}-\d{2}-\d{2}$/.test(d||'')) return d||'TBA'; const x=new Date(d+'T12:00:00'); return x.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}); };
const daysLeft = d => { if(!/^\d{4}-\d{2}-\d{2}$/.test(d||'')) return null; const now=new Date(); now.setHours(0,0,0,0); const x=new Date(d+'T00:00:00'); return Math.ceil((x-now)/86400000); };
const statusText={open:'OPEN',future:'FUTURE',watch:'WATCH',conditional:'CONDITIONAL',unconfirmed:'UNCONFIRMED'};
function card(c){ const days=daysLeft(c.deadline); const soon=days!==null&&days>=0&&days<=30; const deadlineText = fmtDate(c.deadline)+(days!==null&&days>=0?` · ${days} day${days===1?'':'s'} left`: ''); const links=(c.sources||[]).map(s=>`<a class="source" href="${s[1]}" target="_blank" rel="noopener">${s[0]} ↗</a>`).join(''); return `<article class="card" data-year="${c.year}" data-status="${c.status}" data-tier="${c.tier}" data-major="${c.major}" data-search="${[c.name,c.location,c.repertoire,c.video,c.jury,c.note].join(' ').toLowerCase()}">
<div class="card-top"><div class="card-row"><div><div class="eyebrow">${c.year}</div><h3>${c.name}</h3><div class="where">${c.location} · ${c.dates}</div></div><span class="tag ${c.status}">${statusText[c.status]}</span></div></div>
<div class="facts"><div class="fact deadline ${soon?'soon':''}"><label>Application deadline</label><strong>${deadlineText}</strong></div><div class="fact"><label>Application opens</label><strong>${c.opens?fmtDate(c.opens):(c.status==='open'||c.status==='conditional'?'Open / check now':'TBA')}</strong></div><div class="fact"><label>Video / prescreen</label><strong>${c.video.startsWith('Required')?'Required':c.video.startsWith('No ')?'Not stated':'See details'}</strong></div><div class="fact"><label>Level</label><strong>${c.tier.charAt(0).toUpperCase()+c.tier.slice(1)}</strong></div></div>
<div class="eligibility ${c.eligClass||''}"><strong>Eligibility:</strong> ${c.eligibility}</div><div class="summary">${c.note}</div>
<details><summary>Repertoire, prizes & jury</summary><div class="detail-body"><h4>Video / preselection</h4><p>${c.video}</p><h4>Repertoire</h4><p>${c.repertoire}</p><h4>Prizes / support</h4><p>${c.prizes}</p><h4>Jury</h4><p>${c.jury}</p>${links?`<div class="sources">${links}</div>`:''}</div></details></article>`; }

const cards=document.getElementById('cards'); cards.innerHTML=competitions.map(card).join('');
document.getElementById('countAll').textContent=competitions.length; document.getElementById('countOpen').textContent=competitions.filter(c=>['open','conditional'].includes(c.status)).length; document.getElementById('countMajor').textContent=competitions.filter(c=>c.major).length;
const sorted=[...competitions].sort((a,b)=>{const ad=/^\d/.test(a.deadline)?a.deadline:'9999',bd=/^\d/.test(b.deadline)?b.deadline:'9999';return ad.localeCompare(bd)});
document.getElementById('calendarBody').innerHTML=sorted.map(c=>`<tr><td><strong>${fmtDate(c.deadline)}</strong></td><td>${c.name}</td><td>${c.dates}</td><td>${c.location}</td><td><span class="tag ${c.status}">${statusText[c.status]}</span></td></tr>`).join('');
let filter='all'; const search=document.getElementById('search'); function apply(){ const q=search.value.trim().toLowerCase(); document.querySelectorAll('#cards .card').forEach(el=>{let ok=filter==='all'||(filter==='major'&&el.dataset.major==='true')||(filter==='watch'&&['watch','unconfirmed'].includes(el.dataset.status))||(filter==='secondary'&&['secondary','development'].includes(el.dataset.tier))||el.dataset.status===filter||el.dataset.year===filter; if(q&&!el.dataset.search.includes(q)) ok=false; el.classList.toggle('hidden',!ok);});}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;apply();}));search.addEventListener('input',apply);